[[item]]
    code = "beer"
    rarity = "COMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "STRENGTH"

    [item.locales.RU]
    name = "Пиво"
    consumeTemplate = [
        "Кружка пива для нашего постоянного гостя <b>${personage_badge_with_name}</b>",
        "Нет ничего лучше кружки прохладного пива после тяжёлого дня. Верно, <b>${personage_badge_with_name}</b>?",
        "Пивка! Для рывка!",
        "Губит людей не пиво. Губит людей вода!"
    ]

    [item.locales.EN]
    name = "Beer"
    consumeTemplate = [
        "A beer mug for our regular guest <b>${personage_badge_with_name}</b>",
        "There is nothing better than a mug of cool beer after a hard day. Right, <b>${personage_badge_with_name}</b>?"
    ]

[[item]]
    code = "slime_nastoyka"
    rarity = "RARE"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Настойка на слаймах"
    consumeTemplate = [
        "Я смотрю, <b>${personage_badge_with_name}</b> знает толк в качественной выпивке! И слаймах.",
        "Настойка на слаймах, пойманных в окрестностях Крезара. Утром даже голова не болит! Но от других побочек никто не застрахован..."
    ]

    [item.locales.EN]
    name = "Tincture on slimes"
    consumeTemplate = [
        "I see <b>${personage_badge_with_name}</b> knows a lot about quality booze! And slime.",
        "Tincture on slimes caught in the vicinity of Krezar. It's not even a headache in the morning! But no one is immune from other side effects..."
    ]

[[item]]
    code = "grechka_tea"
    rarity = "COMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "AGILITY"

    [item.locales.RU]
    name = "Гречкин чай"
    consumeTemplate = [
        "Нет не из гречихи, да на гречке, угощайтесь, <b>${personage_badge_with_name}</b>.",
        "Теплый напиток со вкусом обеда - готов!"
    ]

    [item.locales.EN]
    name = "Buckwheat tea"
    consumeTemplate = [
        "Fresh buckwheat, treat yourself, <b>${personage_badge_with_name}</b>.",
        "A warm drink with the taste of lunch is ready!"
    ]

[[item]]
    code = "monastery_wine"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Монастырское вино"
    consumeTemplate = [
        "Ароматный букет ладана и масла защищает душу и тело от происков врагов.",
        "Вино категорически запрещено в употребление демонам и нежити. Но тебе же нечего бояться, правда?"
    ]

    [item.locales.EN]
    name = "Monastery wine"
    consumeTemplate = [
        "A fragrant bouquet of incense and oil protects the soul and body from the machinations of enemies.",
        "Wine is strictly forbidden for use by demons and undead. But you have nothing to be afraid of, right?"
    ]

[[item]]
    code = "gorgon"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Горгоний соблазн"
    consumeTemplate = [
        "Настойка на змеином яде, ее можно не только пить, но и втирать в колени!",
        "Таверна не несёт ответственности в случае частичного превращения в камень. За твоё здоровье!"
    ]

    [item.locales.EN]
    name = "Gorgon temptation"
    consumeTemplate = [
        "Tincture of snake venom, you can not only drink it, but also rub it into your knees!",
        "The tavern is not responsible in case of partial transformation into stone. To your health!"
    ]

[[item]]
    code = "cat_soup"
    rarity = "UNCOMMON"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Суп с котом"
    consumeTemplate = [
        "Суп с котом для <b>${personage_badge_with_name}</b>! Мяукал ещё 15 минут назад"
    ]

    [item.locales.EN]
    name = "Cat soup"
    consumeTemplate = [
        "Cat soup for <b>${personage_badge_with_name}</b>! Meowed 15 minutes ago"
    ]

[[item]]
    code = "roast_maggoose"
    rarity = "RARE"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Жаркое из маггуся"
    consumeTemplate = [ "Жаркое из свежего маггуся! Повышает магическую потенцию" ]

    [item.locales.EN]
    name = "Roast of maggoose"
    consumeTemplate = [ "Roast of fresh maggoose! Increases magical potency" ]

[[item]]
    code = "fried_potato"
    rarity = "COMMON"
    isAvailable = true
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Жареная картошечка"
    consumeTemplate = [
        "Мммм, горячая картошечка... Отжарили ее для <b>${personage_badge_with_name}</b>!",
        "Горячее этой картошечки - только ты!"
    ]

    [item.locales.EN]
    name = "Fried potatoes"
    consumeTemplate = [ "Only you are hotter than this potato!" ]

[[item]]
    code = "olivier"
    rarity = "RARE"
    isAvailable = false
    category = "MAIN_DISH"
    effectCharacteristic = "HEALTH"

    [item.locales.RU]
    name = "Оливье"
    consumeTemplate = [
        "Домашний салатик, приготовленный с любовью!",
        "<b>${personage_badge_with_name}</b>, куда делся тазик оливье?",
        "Такой салат ещё вкуснее рядом с хорошими товарищими. Хорошо, что <b>${personage_badge_with_name}</b> один из них!",
    ]

[[item]]
    code = "champagne"
    rarity = "RARE"
    isAvailable = false
    category = "DRINK"
    effectCharacteristic = "WISDOM"

    [item.locales.RU]
    name = "Шампанское"
    consumeTemplate = [
        "Звон бокалов ласкает слух!",
        "С Новым Годом, <b>${personage_badge_with_name}</b>!",
        "С каждым глотком настроение становится более праздничным! Поделись им с друзьями",
        "Праздник к нам приходит, праздник к нам приходит! А вместе с ним и пьяный <b>${personage_badge_with_name}</b>!",
        "Счастья! Здоровья! Что б меч стоял, и деньги были!"
    ]

[[item]]
    code = "gluhwein"
    rarity = "RARE"
    isAvailable = false
    category = "DRINK"
    effectCharacteristic = "ATTACK"

    [item.locales.RU]
    name = "Глинтвейн"
    consumeTemplate = [
        "Согревает душу и тело <b>${personage_badge_with_name}</b>!",
        "Лучшее вино, свежие апельсины и секретные специи пострадали, чтобы оказаться в стакане <b>${personage_badge_with_name}</b>.",
        "Отличный напиток для этой холодной погоды!",
        "Год был не простым... Но <b>${personage_badge_with_name}</b> был на высоте!",
    ]
