[[raid]]
code = "dragon"
isEnabled = true

[raid.info]
health = 200000
attack = 100
defense = 300
strength = 9
agility = 7
wisdom = 5

[raid.locales.RU]
intro = """\
Это птица? Это огненный шар? Это дракон! ДРАКОН???????

Этих тварей истребили ещё до появления Империи на карте мира. Не знаем откуда он взялся \
в окрестностях Крезара, однако необходимо срочно уничтожить его, пока он не начал нападать \
на мирное население."""

[[raid]]
code = "swamp-thing"
isEnabled = true

[raid.info]
health = 300000
attack = 80
defense = 400
strength = 15
agility = 1
wisdom = 1

[raid.locales.RU]
intro = """\
Обнаружена мерзкая болотная тварь!

Похоже на мутировшую слизь. Умом и сообразительностью не отличается, зато очень даже отличается \
агрессивностью и живучестью. Несколько крестьян уже успели стать её жертвами, пока ходили в лес за грибами. \
Убейте её, пока жертв не стало больше."""
