duelMustContainsMention = "The duel should be a reply to another user's message"
duelWithDifferentBot = [
    "Choose someone more lively as your opponent!"
]
duelWithThisBot = [
    "I do not advise you to start a fight with the staff! Otherwise, there may be a special foam from the waiter in your beer"
]
duelWithYourself = "You can't have a duel with yourself!"
duelWithInitiatorNotEnoughMoney = [
    """\
Whoa! To use the arena, you need at least ${money_icon}${money_count}. Go work for a start"""
]
personageAlreadyStartDuel = "You have already started another duel! Wait for it to finish."
notDuelAcceptingPersonage = "It wasn't you who was challenged to a duel!"
expiredDuel = [
    "The challenge to the duel was ignored"
]
declinedDuel = [
    "The accepting party rejected the call!"
]
finishedDuel = [
    """\
The seeker ${mention_winner_icon_with_name} got the better of \
${mention_loser_icon_with_name}"""
]
acceptDuelButton = "Take the challenge🗡"
declineDuelButton = "Decline👐"
