joinRaidEvent = "Join raid🗡(${energy_icon}${energy_cost}%)"
raidStartsPrefix = "The battle will begin in"
userAlreadyInOtherEvent = "You are already participating in another event!"
expiredRaid = "This event is over!"
successRaid = [
    "Raid was successful."
]
failureRaid = [
    "The seekers failed the raid."
]
