chooseLanguage = "Тілді таңдаңыз:"
onlyAdminAction = "Бұл әрекет тек администраторларға ғана қолжетімді"
internalError = "Қате, кейінірек қайталап көріңіз"

hoursShort = "сағ."
minutesShort = "мин."

# текста для группы
groupStats = """\
📊<b>Группаның статистикасы:</b>

🗡Сәтті рейдтер: ${raids_count}
🤺Аяқталған дуэльдер: ${duels_count}

🍻Тавернада жұмсалды: ${money_icon}${tavern_money_spent}
"""
personageGroupStats = """\
📊<b>Сіздің группадағы статистикаңыз:</b>

🗡Сәтті рейдтер: ${raids_success}/${raids_total}
🤺Жеңген дуэльдер: ${duels_wins}/${duels_total}

🍻Тавернада жұмсалды: ${money_icon}${tavern_money_spent}
⚒Бүгінгі күннің үздік жұмыскері: ${spin_wins_count}
"""

# текста для лички
receptionDesk = "Сәлеметсіз бе! Көмегім қажет пе?"
