chooseLanguage = "Тілді таңдаңыз:"
onlyAdminAction = "Бұл әрекет тек администраторларға ғана қолжетімді"
internalError = "Қате, кейінірек қайталап көріңіз"

hoursShort = "сағ."
minutesShort = "мин."

# текста для лички
receptionDesk = "Сәлеметсіз бе! Көмегім қажет пе?"
