welcomeGroup = """\
Приветствую вас в таверне города Крезар, Искатели! Быстро введу вас в курс дела:

⚔️ Участвуйте в рейдах, чтобы заработать золото и снаряжение! Расписание рейдов доступно по команде ${settings_command}.
🍻 Пейте в таверне со своими товарищами! Текущее меню можно посмотреть здесь ${menu_command}
🤺 Сразитесь на дуэли с помощью ${duel_command} и выясните кто прав.
⚒ Выбирайте ответственного работягу каждый день в ${spin_command}.
🏆 Соревнуйтесь в топах! ${top_command}
💬 Заходите в @${bot_username}, чтобы сходить в квесты, прикупить снаряжение, сменить имя или для других занятий.

Жмите ${help_command} если возникнут дополнительные вопросы. \
И заходите в ${news_channel_username}, чтобы не пропустить обновления!"""

chooseLanguage = "Выберите язык:"
onlyAdminAction = "Данное действие доступно только администраторам"
forbiddenForHiddenGroup = "Данное действие недоступно в скрытой группе"
onlyForRegisteredGroup = "Данное действие доступно только в зарегистрированных гурппах"
forbiddenAction = "Ты не можешь этого сделать"
internalError = "Произошла ошибка, попробуйте позже"
fullProfile = """\
${personage_badge_with_name}
${money_icon}Золото: ${personage_money}
${energy_icon}Энергия: ${energy_value}% ${time_icon}${remain_duration_for_full_regen}
${health_icon}Здоровье: ${health_value}
${attack_icon}${attack_value} ${defense_icon}${defense_value}
${strength_icon}${strength_value} ${agility_icon}${agility_value} ${wisdom_icon}${wisdom_value}
${current_event}${personage_effects}
👤Снаряжение: ${item_characteristics}"""

shortProfile = """\
${personage_badge_with_name}
${money_icon}${personage_money} ${energy_icon}${energy_value}%
${health_icon}${health_value} ${attack_icon}${attack_value} ${defense_icon}${defense_value}
${strength_icon}${strength_value} ${agility_icon}${agility_value} ${wisdom_icon}${wisdom_value}"""

# Отступы нужны, чтобы нормально отображалось в fullProfile
personageEffects = """\
\nЭффекты:${personage_effects}
""" # здесь нужен перенос, чтобы была строчка до снаряжения
menuItemEffect = "\n<code>-🍻Таверна: ${effect} ${time_icon}${duration}</code>"
throwOrderEffect = "\n<code>-⭕️Метание заказов: ${effect} ${time_icon}${duration}</code>"
addValueEffect = "+${value}${characteristic_icon}"
multiplyPercentEffect = "+${value}%${characteristic_icon}"
minusMultiplyPercentEffect = "-${value}%${characteristic_icon}"

personageInRaid = "\nВ рейде ${time_icon}${duration}\n"
personageInQuest = "\nВ квесте ${time_icon}${duration}\n"

hoursShort = "ч."
minutesShort = "мин."

# текста для группы
groupStats = """\
📊<b>Статистика группы ${group_name_with_badge}:</b>

🗡Успешные рейды: ${raids_count}
🤺Завершено дуэлей: ${duels_count}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
"""
personageGroupStats = """\
📊<b>Твоя статистика в группе:</b>

🗡Успешные рейды: ${raids_success}/${raids_total}
🤺Победы в дуэлях: ${duels_wins}/${duels_total}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
⚒Работяга дня: ${spin_wins_count}
"""
personageGlobalStats = """\
📊<b>Твоя статистика в тавернах Крезара:</b>

🗡Успешные рейды: ${raids_success}/${raids_total}
🤺Победы в дуэлях: ${duels_wins}/${duels_total}
📝Успешные квесты: ${quests_success}/${quests_total}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
⚒Работяга дня: ${spin_wins_count}
"""

migrateGroup = """\
Техническое сообщение: группа преобразована в супергруппу. Статистика перенесена"""

# текста для лички
# TODO перенести куда-нибудь
welcomeUser = """
Добро пожаловать в таверну, Искатель!

Здесь тебе доступны разнообразные активности:
⚔️ Участвуй в рейдах, чтобы заработать золото и снаряжение!
🍻 Пей в таверне со своими товарищами!
🤺 Сразись на дуэли и покажи кто здесь главный.
💬 И другие занятия в тавернах славного города Крезар!

Чтобы сделать свой опыт интереснее, добавь бота в группу с друзьями и играйте вместе! \
Ходить по тавернам в одиночку довольно грустно...

Ты можешь нажать ${help_command}, чтобы ознакомиться подробнее с текущим положением дел.
Присоединяйся к ${news_channel_username} чтобы не пропустить свежие новости."""
receptionDesk = """\
На стене за стойкой ты видишь надпись, сотканную из потоков маны:

🔰Активные Искатели за сутки: ${active_personages_count}
👥Активные Группы: ${active_groups_count}

Ты можешь обратиться к персоналу по следующим вопросам:"""
energyRecovered = [
    "Энергия восстановлена! Иди займись чем-нибудь полезным",
    "Ты уже достаточно отдохнул и полон сил, хватит отлынивать"
]
