welcomeGroup = """\
Приветствую вас в таверне города Крезар, Искатели! \
Присаживайтесь за стол, заказывайте выпить, чувствуйте себя как дома
"""
chooseLanguage = "Выберите язык:"
onlyAdminAction = "Данное действие доступно только администраторам"
internalError = "Произошла ошибка, попробуйте позже"
fullProfile = """\
${personage_badge_with_name}
${money_icon}Золото: ${personage_money}
${energy_icon}Энергия: ${energy_value}% ${time_icon}${remain_duration_for_full_regen}
${health_icon}Здоровье: ${health_value}
${attack_icon}${attack_value} ${defense_icon}${defense_value}
${strength_icon}${strength_value} ${agility_icon}${agility_value} ${wisdom_icon}${wisdom_value}
${current_event}${personage_effects}
👤Снаряжение: ${item_characteristics}"""

shortProfile = """\
${personage_badge_with_name}
${money_icon}${personage_money} ${energy_icon}${energy_value}%
${health_icon}${health_value} ${attack_icon}${attack_value} ${defense_icon}${defense_value}
${strength_icon}${strength_value} ${agility_icon}${agility_value} ${wisdom_icon}${wisdom_value}"""

# Отступы нужны, чтобы нормально отображалось в fullProfile
personageEffects = """\
\nЭффекты:
${personage_effects}
"""
menuItemEffect = "<code>-🍻Таверна: ${effect} ${time_icon}${duration}</code>"
addValueEffect = "+${value}${characteristic_icon}"
multiplyPercentEffect = "+${value}%${characteristic_icon}"

personageInRaid = "\nВ рейде ${time_icon}${duration}\n"
personageInQuest = "\nВ квесте ${time_icon}${duration}\n"

hoursShort = "ч."
minutesShort = "мин."

# текста для группы
groupStats = """\
📊<b>Статистика группы:</b>

🗡Успешные рейды: ${raids_count}
🤺Завершено дуэлей: ${duels_count}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
"""
personageGroupStats = """\
📊<b>Твоя статистика в группе:</b>

🗡Успешные рейды: ${raids_success}/${raids_total}
🤺Победы в дуэлях: ${duels_wins}/${duels_total}

🍻Потрачено в тавернe: ${money_icon}${tavern_money_spent}
⚒Работяга дня: ${spin_wins_count}
"""

migrateGroup = """\
Техническое сообщение: группа преобразована в супергруппу. Статистика перенесена"""

# текста для лички
# TODO перенести куда-нибудь
welcomeUser = "Добро пожаловать в таверну, Искатель!"
receptionDesk = """\
На стене за стойкой ты видишь надпись, сотканную из потоков маны:

🔰Активные Искатели за сутки: ${active_personages_count}
👥Активные Группы: ${active_groups_count}

Ты можешь обратиться к персоналу по следующим вопросам:"""
energyRecovered = [
    "Энергия восстановлена! Иди займись чем-нибудь полезным",
    "Ты уже достаточно отдохнул и полон сил, хватит отлынивать"
]
