initFeedback = """\
Добро пожаловать в систему обратной связи Krezar Tavern.
Здесь принимаются все предложения по улучшению, сообщения об ошибках и прочие вопросы связанные с игрой.

За дельные обращения вы можете получить в награду внутриигровую валюту или жетоны. Пожалуйста, избегайте спама.

Выберите тему для обращения:"""

errorButton = "❗️Сообщить об ошибке"
improvementButton = "💡Предложить идею"
textButton = "📝Предложить текст"
otherButton = "💬Другое"
backButton = "⬅️Назад"

inputTextSuggestion = """\
Здесь можно предложить любой текст для игры. Неполный список такой:
Рейды, квесты, позиции в таверне, конец рейда, начало дуэли, конец дуэли, просроченный заказ, работяга дня, \
заказ в таверне, угощение в таверне и вообще всё, что вы видете в игре в виде текста."""
inputFeedback = "Введите текст обращения:"
feedbackSent = """\
Сообщение отправлено разработчику. Если оно будет достойным внимания, то \
обратная связь будет на канале ${feedback_channel}."""
feedback = """\
<code>${personage_id} ${personage_badge_with_name}</code>

${feedback_theme}

${feedback_text}"""
cancelFeedback = "Не в этот раз."
invalidTheme = "Выберите тему из списка:"
feedbackErrorSent = "Не удалось отправить сообщение. Пожалуйста, повторите попытку позже."
