registeredGroupInfo = """\
<code>${group_name_with_badge}</code>

Казна: ${money}${money_icon}
Участники: ${members_count}

📊Статистика группы: ${group_stats_command}
⚙️Настройки: ${group_settings_command}
Комманды для группы: ${group_commands_command}
"""
unregisteredGroupInfo = """\
<code>${group_name_with_badge}</code>

Казна: ${money}${money_icon}

Зарегистрировать группу: ${register_group_command}

📊Статистика группы: ${group_stats_command}
⚙️Настройки: ${group_settings_command}
Вложить деньги: <code>${donate_money_command} [сумма]</code>
"""

groupRegistration = """\
Для регистрации группы необходимо установить тэг группы <code>${register_group_command} тэг</code>. \
Тэг должен стостоять из 3-4 заглавных букв латинского алфавита.
Стоимость: ${money}${money_icon}"""
alreadyRegisteredGroup = "Группа уже зарегистрирована"
registrationPersonageInAnotherGroup = "Регистрирующий персонаж не должен быть участником другой группы!"
notEnoughMoneyForGroupRegistration = "Для регистрации группы необходимо ${money}${money_icon} в казне группы!"
incorrectTag = "Неправильно указан тэг, он должен состоять из 3-4 заглавных букв латинского алфавита"
tagAlreadyTaken = "Такой тэг уже занят"
successGroupRegistration = "Группа успешно зарегистрирована! Вступить в группу можно с помощью ${group_join_command}"

joinPersonageAlreadyInGroup = "Ты уже состоишь в этой группе!"
joinPersonageInAnotherGroup = "Ты уже состоишь в другой группе!"
groupNotRegisteredAtJoin = "Группа должна быть зарегистрирована для вступления: ${register_group_command}"
successJoinGroup = "<code>${personage_badge_with_name}</code> теперь состоит в группе <code>${group_name_with_badge}</code>!"

leaveGroupSuccess = "<code>${personage_badge_with_name}</code> больше не состоит в группе"
leaveGroupNotMember = "Ты не состоишь в этой группе"
leaveGroupLastMemberConfirmation = "После тебя в группе не будет участников, и она будет снята с регистрации"
leaveGroupConfirmButton = "✅Покинуть"
leaveGroupCancelButton = "❌Отменить"
leaveGroupLastMemberSuccess = """
<code>${personage_badge_with_name}</code> больше не состоит в группе. \
<code>${group_name_with_badge}</code> снята с регистрации"""
leaveGroupCancel = "Ты остаёшься в группе"

successDonate = "В группу вложено ${money}${money_icon} от ${personage_badge_with_name}!"
notEnoughMoneyForDonate = "Недостаточно денег"
successTakeMoney = "Из группы взято ${money}${money_icon} в пользу ${personage_badge_with_name}!"
notEnoughMoneyForTake = "Недостаточно денег в казне группы"
takeMoneyPersonageNotMember = "Нужно состоять в группе, чтобы взять из неё деньги"
incorrectAmount = "Неправильно указана сумма"

groupCommands = """\
Комманды для группы:

<code>${group_join_command}</code> - вступить в группу
<code>${group_leave_command}</code> - покинуть группу
<code>${donate_money_command} [сумма]</code> - вложить деньги в группу
<code>${take_money_command} [сумма]</code> - взять деньги из группы"""
