main = """\
Добро пожаловать в таверну города Крезар!

Здесь ты можешь отдохнуть, выпить или доказать, что кто-то не прав, вызвав его на дуэль. \
Также можно заработать немного золота в рейдах.

Не стесняйся обращаться за помощью, мы с радостью тебе поможем.
"""

raids = """\
Для того, чтобы участвовать в рейдах, необходимо добавить бота в свою группу.
После этого, в определённые промежутки времени (<code>${settings_command}</code>) в таверне будут появляться объявления, \
за участие в которых можно заработать денег. Если рейд завершится успехом, то и награда возрастёт.

И помните! Чем больше искателей, тем выше шанс на победу!

Каждый раз, когда вы участвуете в рейде, ваша ${energy_icon}Энергия уменьшается, а после постепенно восстанавливается."""

duels = """\
Если тебе кажется, что в таверне кто-то не прав, то за таверной есть специальная арена для выяснения отношений!
Просто ответь на сообщение обидчика с помощью ${duel_command}.

Однако знай, что арена — это не бесплатное удовольствие! Кто-то же должен отмыть её потом от крови и убрать выбитые зубы.
"""

menu = """\
Как и в любой уважающей себя таверне, у нас можно выпить и вкусно покушать.

Ознакомься со списком доступных позиций через ${menu_command} и заказывай то, что тебе понравилось!
Ты можешь также угостить своего друга: ответом на сообщение \
или через упоминание в заказе <code>${order_command}1 @user</code>.

После того как ты закончишь есть и пить, ты можешь кинуть посуду в своего раздражающего друга с помощью ${throw_command}.
Или кинуть её в другую группу с помощью <code>${throw_to_group_command} тэг</code>
"""

personage = """\
Перейдя в ${bot_username}, ты можешь воспользоваться стойкой регистрации.

Там ты сможешь сменить своё имя с помощью магического круга.
Или можешь заплатить за доступ к книге забвения, чтобы забыть свои боевые навыки и выучить новые.
"""

info = """\
Новости проекта можно найти на этом канале: ${news_channel_username}.

Исходный код игры находится <a href="${source_code_link}">здесь</a>.
Также по этой ссылке можно найти, как помочь переводу контента на другие языки.
"""

battleSystem = """\
Характеристики персонажа:
${health_icon}Здоровье ${attack_icon}Атака ${defense_icon}Защита
${strength_icon}Сила ${agility_icon}Ловкость ${wisdom_icon}Мудрость

Правила боя:
1. Если ${health_icon}Здоровье опускается до 0, персонаж погибает.
2. ${strength_icon}Сила имеет преимущество над ${agility_icon}Ловкостью.
3. ${agility_icon}Ловкость имеет преимущество над ${wisdom_icon}Мудростью.
4. ${wisdom_icon}Мудрость имеет преимущество над ${strength_icon}Силой.
5. ${strength_icon}Сила влияет на ${normal_attack_icon}обычные атаки.
6. ${agility_icon}Ловкость влияет на шанс ${dodge_icon}уклонения.
7. ${wisdom_icon}Мудрость влияет на шанс ${crit_attack_icon}критического урона.
8. ${attack_icon}Атака влияет на весь наносимый урон.
9. ${defense_icon}Защита позволяет выдержать больше урона.
10. Бой происходит в пошаговом режиме. За один ход персонаж совершает один удар.
"""

seasons = """\
⚡ Каждый сезон начинается с разрушительного магического шторма, который смывает большую часть накопленных средств \
и ломает снаряжение Искателей.

🔥 После шторма начинается новый сезон! Все активные Искатели прошлого сезона получают специальный жетон, \
а в тавернах вывешивают списки лучших из лучших, чтобы отметить их подвиги.

📣 Следите за свежими новостями и обновлениями здесь: ${news_channel_username}!
"""


raidsButton = "🗡Рейды"
duelsButton = "🤺Дуэли"
menuButton = "🍻Таверна"
personageButton = "🔰Искатель"
infoButton = "💬Прочее"
battleSystemButton = "⚔️Боёвка"
seasonsButton = "⚡️Сезоны"
