[menu]
profileButton = "👤Профиль"
languageButton = "🌐Язык"
receptionDeskButton = "✍️Стойка регистрации"
backButton = "⬅️Назад"
resetCharacteristicsButton = "📖Книга забвения"
changeNameButton = "🔮Сменить имя"
showBadgesButton = "🔰Жетоны"
inventoryButton = "🎒Инвентарь"
shopButton = "⚖️Чёрный рынок"
bulletinBoardButton = "📣Доска объявлений"
takePersonalQuestButton = "📝Взять квест"
worldRaidButton="🔎Мировой рейд"

[changeName]
changeNameWithoutName="Имя не может быть пустым!"
initChangeName = """
Использование магического круга обойдётся в ${change_name_cost}${money_icon}. Необходимо написать имя, под которым тебя будут знать другие Искатели.
Разрешённые символы: <code>кириллица, латиница, цифры, _-.#№ и пробел</code>
"""
notEnoughMoney = "Для смены имени необходимо: ${change_name_cost}${money_icon}"
repeatChangeName = "Введи новое имя:"
cancelChangeName = "Магический круг затухает. В другой раз..."
confirmName = "Твоё новое имя: <code>${name}</code>. Правильно?"
personageNameInvalidLength = """\
Прости, но в магическом круге есть ограничение на символы в имени. От ${min_name_length} до ${max_name_length} символов"""
personageNameInvalidSymbols = """\
К сожалению, в магическом круге для сохранения имени можно использовать только: \
<code>кириллицу, латиницу, цифры, символы _-.#№ и пробел</code>"""
successNameChange = "Имя успешно изменено! Магический круг затухает."
internalError = "Магический круг начинает мерцать и резко затухает. Похоже произошла ошибка, попробуйте позже."
cancelButton = "❌Отказаться"
confirmButton = "✅Всё верно"
repeatButton = "🔄Ещё раз"

[characteristics]
resetConfirmation = """\
Для того, чтобы прочесть книгу забвения необходимо заплатить ${money_icon}${money_count}. \
Ты точно хочешь забыть свои старые навыки?"""
successReset = """\
После прочтения книги сознание затуманивается... Ты забываешь свои старые навыки. Перед тобой снова открыты все пути."""
canceledReset = "Книга останется здесь. Приходи, когда решишься"
increasedCharacteristic = "Ты улучшил навык: ${increased_value}${increased_icon}."
currentCharacteristics = """\
Текущие характеристики: ${strength_value}${strength_icon}${agility_value}${agility_icon}${wisdom_value}${wisdom_icon}"""
chooseCharacteristic = """\
Выбери, что ты хочешь изучить:
(${strength_icon}>${agility_icon}>${wisdom_icon}>${strength_icon})"""
notEnoughCharacteristicPoints = "Ты достиг своего предела! Если захочешь изменить стиль боя, воспользуйся книгой забвения."
notEnoughMoney = "Книга забвения тебе не по карману! Нужно ${money_icon}${money_count}"
profileLevelUp = "Ты можешь улучшить свои навыки! Жми ${level_up_command}"
confirmButton = "📖Прочесть"
cancelButton = "❌В другой раз"
strengthButton = "+1${strength_icon}"
agilityButton = "+1${agility_icon}"
wisdomButton = "+1${wisdom_icon}"

[badges]
availableBadges = """\
Доступные жетоны:

${badge_list}"""
badge = """\
${badge_icon} ${badge_description}"""
badgeIsNotAvailable = "Данный жетон недоступен"

[bulletinBoard]
bulletinBoard = """\
На доске висит множество объявлений от жителей Крезара. Выбери одно, и в случае успеха получишь награду.

Затраты на квест: ${energy_icon}${quest_required_energy}% ${time_icon}${quest_duration}
Взять несколько квестов: <code>${take_quest_command} N</code>"""
notEnoughEnergy = "Для начала квеста необходимо: ${energy_icon}${required_energy}%"
personageInAnotherEvent = "Ты уже занят в другом событии."
startedQuest = """\
${quest_intro}

Ты потратишь ${energy_icon}${energy}% и вернёшься через ${time_icon}${duration}"""
autoStartedQuest = """\
${energy_recovered}

${started_quest}
"""
failedSingleQuest = """\
${quest_failure}

Текущая энергия: ${energy_icon}${current_energy}%"""
successSingleQuest = """\
${quest_success}

Ты получаешь +${money_icon}${money_value}
Текущая энергия: ${energy_icon}${current_energy}%"""
incorrectQuestCount = "Необходимо ввести целое число >=1."
multipleQuestsIntro = [
    "Ты срываешь пачку объявлений с доски и отправляешься работать.",
    "Сильная нужда побуждает работать больше, поэтому ты пихаешь себе в карман сразу несколько объявлений.",
    "Глядя на доску объявлений, ты понимаешь: если не возьмёшь все квесты сразу, то они могут закончиться!",
    "Отдохнуть можно и в старости, а сейчас надо сделать побольше квестов, пока их не разобрали.",
]
multipleQuestsFinished = """\
${multiple_quests_outro}

${quests_results}

Ты получаешь +${money_icon}${money_value}
Текущая энергия: ${energy_icon}${current_energy}%"""
multipleQuestsOutro = [
    "После такого количества квестов можно и пивка бахнуть!",
    "Все задания завершены! Не обязательно успешно, но главное ведь количество?",
]

worldRaidResearch = """\
Прогресс поиска рейда: ${progress}%
Фонд: ${money_icon}${fund_value}

Увеличить прогресс:
• Сходить в квест
• Сделать пожертвование ${money_icon}${donate_value} ${donate_world_raid_command}

📊Топ Искателей по вкладу: ${world_raid_research_top_command}"""
worldRaidBattle = """\
Противник обнаружен! Всем участникам зарегистрированных групп просьба присоединиться к битве ${world_raid_channel}

Фонд: ${money_icon}${fund_value}

📊Топ Искателей по вкладу: ${world_raid_research_top_command}"""
notEnoughMoneyForDonate = "Недостаточно средств для пожертвования. Нужно ${money_icon}${required_value}"
worldRaidResearchIsCompleted = "Поиск рейда уже завершён!"
successWorldRaidDonate = "Пожертвование принято! ${money_icon}${money_value} добавлено к фонду"

[settings]
personageIsHidden = "Ты был скрыт из глобальных рейтингов и статистики. Оставайся в тени."
personageIsUnhidden = "Твои достижения вновь доступны для всех искателей."
settings = """\
⚙️Настройки:

Уведомления — присылать уведомления о фоновых событиях: восстановление энергии, квесты и т.д.
Автоматические квесты — автоматически отправляться в квест при полной энергии. Это отнимает больше энергии."""
sendNotificationsButton = "${enabled_icon}Уведомления"
autoQuestingButton = "${enabled_icon}Автоматические квесты"
