menuHeader = "Сегодня в меню:"
drinks = "Напитки"
mainDishes = "Основные блюда"
itemNotInMenu = "Такой позиции нет в меню!"
notEnoughMoneyDrink = [
    "Тебе не хватает ${money_icon}${not_enough_money_value}, иди поработай, потом приходи пить!",
    "Данный напиток тебе явно не по карману! Он стоит ${money_icon}${item_cost}"
]
notEnoughMoneyMainDish = [
    "Кто не работает, тот не ест! Заработай ещё ${money_icon}${not_enough_money_value}"
]
orderGiftToDifferentBot = [
    "Прости, но заказы для неодушевлённых предметов не принимаются"
]
orderDrinkToThisBot = [
    "Бармену не наливать",
    "Этот симпатичный официант не пьёт на работе, дождись окончания его смены",
]
orderMainDishToThisBot = [
    "Официант сыт",
    "Неужели ты думаешь, что персонал не кормят?",
    "Лучше сам покушай перед рейдом",
]
order = [
    "${item_name} для ${mention_acceptor_icon_with_name}!"
]
orderGift = [
    "Заказ! ${item_name} от ${mention_giver_icon_with_name} для ${mention_acceptor_icon_with_name}"
]
expiredOrder = [
    "Заказ так долго стоял без дела, что его съел голодный официант. Денег он, к сожалению, не оставил."
]
consumeDrinkButton = "🍺Выпить"
consumeMainDishButton = "🍽Съесть"
consumeAlreadyInFinalStatus = "Заказ куда-то испарился... Возможно его утащил бабайка"
consumed = """\
${consumed_item_text}
<i>Эффект: ${effect}</i>"""
wrongConsumer = "Это не твой заказ!"
orderToUnknownUser = [
    """\
Официанты не нашли этого Искателя среди посетителей. \
Возможно твой товарищ ещё не посещал данную таверну или сменил имя."""
]
orderIsLocked = "Заказ в обработке, попробуйте позже."

# THROW ORDER
userNotFoundToThrow = "Ты оглядываешься по сторонам, но не можешь никого найти. Пусть твой товарищ нажмёт ${get_profile_command}"
noOrdersToThrow = "Ты оглядываешь стол, но ничего на нём не находишь. Закажи себе что-нибудь в ${menu_command}."
onlyCreatedDish = [
    "В прошлый раз когда кто-то кидался едой, персонал избил его до полусмерти. Доешь сначала до конца.",
]
onlyCreatedDrink = [
    "Жаль оставлять такую вкуснятину. Стоит допить.",
]
notEnoughMoneyToThrow = [
    "Ты смотришь на посуду, на деньги в своём кармане. Ставишь посуду на место.",
    "Если не хватит денег расплатиться за битую посуду, придётся отдавать натурой. Тебе это не понравится.",
]
throwResult = """\
${throw_text}

<i>Потрачено: -${money_value}${money_icon}${optional_effect}</i>"""
throwEffect = "\nЭффект: ${effect}"

throwDishToNone = [
    "Тарелка со звоном разбивается об ближайшую стену",
    "Персонал с грустью убирает осколки посуды... Ни стыда, ни совести.",
    "А ведь это была любимая тарелка Аннушки",
]
throwDrinkToNone = [
    "Стакан со звоном разбивается об ближайшую стену",
    "Ты со всей силы разбиваешь кружку об пол. Все отделались лёгким испугом.",
]
throwDishToPersonage = [
    "Тарелка как фрисби влетает в ${mention_target_icon_with_name}.",
    "Ты с размаху разбиваешь тарелку об голову ${mention_target_icon_with_name}. Похоже на сотрясение.",
]
throwDrinkToPersonage = [
    """\
    Кружка летит через весь зал чётко в ${mention_target_icon_with_name}. \
    Зрители аплодируют, а ты платишь за битьё посуды""",
    "Бокал оказался не лучшим оружием в бою с ${mention_target_icon_with_name}. Но не бесполезным.",
]
selfThrowDish = [
    "Ты бьёшься головой об стол и разбиваешь стоящую там тарелку. Гений.",
]
selfThrowDrink = [
    "Поспорил, что разобьёшь бутылку об голову без повреждений. Слабоумие и отвага.",
]
throwToStaff = [
    "Случайно попал посудой в бармена. Очнулся на улице.",
    "Решил отомстить официанту и кинуть в него чем-нибудь. Тебя жёстко отмудохали толпой.",
]

throwToGroupMissingGroup = "Необходимо указать тэг группы <code>${throw_to_group_command} тэг</code>"
throwToGroupNotExists = "Такой группы не существует"
throwToGroupNotMember = "Ты не состоишь в группе, из которой собираешься бросить заказ"
throwToGroupTimeout = "За вашей группой пристально наблюдают после последнего инцидента. Лучше подождать ${duration}"
throwToGroupTargetTimeout = "Похоже в твою цель недавно прилетело и они настороже. Лучше подождать, если не хочешь тяжкие телесные"
throwToGroupNoPersonage = "Похоже что в <code>${group}</code> пусто и нет мешени. Так не интересно."
throwToThisGroup = "Ты не можешь кинуть в эту же группу"
throwToGroupResult = """\
${throw_text}

<i>Потрачено: -${money_value}${money_icon}</i>"""
throwFromGroupResult = """\
${throw_text}

<i>Эффект: ${effect}</i>"""
throwDrinkToGroup = [
    "Ты кидаешь кружку в толпу <code>${to_group}</code> и попадаешь в голову <code>${personage}</code>! Но приходится оплатить ущерб.",
    "Бросок в <code>${to_group}!</code> Бокал летит.... ГООООООЛ!!!! <code>${personage}</code> в накауте.",
    "С размахом отправляешь кружку в <code>${to_group}</code> — <code>${personage}</code> теперь знает, что такое боль.",
    "Твой бокал летит в <code>${to_group}</code> и с грохотом встречается с <code>${personage}</code>! Аплодисменты от бармена.",
    "Кружка, пущенная тобой в <code>${to_group}</code>, эффектно сбивает с ног <code>${personage}</code>! Публика в восторге.",
    "С криком «За здоровье!» ты отправляешь бокал в <code>${to_group}</code>, и он точно попадает в <code>${personage}</code>.",
]
throwDishToGroup = [
    "Ты кидаешь тарелку в толпу <code>${to_group}</code> и попадаешь в голову <code>${personage}</code>! Но приходится оплатить ущерб.",
    "Бросок в <code>${to_group}!</code> Тарелка летит.... ГООООООЛ!!!! <code>${personage}</code> в накауте.",
    "Тарелка, пущенная тобой в <code>${to_group}</code>, находит свою цель — <code>${personage}</code> теперь украшен остатками ужина.",
    "Тарелка, запущенная в <code>${to_group}</code>, с треском встречается с <code>${personage}</code>! Официант негодует.",
    "Ты метко бросаешь тарелку в <code>${to_group}</code> — <code>${personage}</code> теперь знает, каково быть мишенью.",
    "Твой бросок тарелки в <code>${to_group}</code> вызывает бурю эмоций у <code>${personage}</code> и всей таверны.",
]

throwDrinkFromGroup = [
    "Внезапно из <code>${from_group}</code> прилетает бокал прямо в спящего ${mention_personage}!",
    "Из <code>${from_group}</code> с грохотом прилетает кружка и попадает в ${mention_personage}! Бармен одобряет меткость.",
    "Бокал из <code>${from_group}</code> пролетает через весь зал и приземляется прямо на голову ${mention_personage}!",
    "Из <code>${from_group}</code> прилетает кружка — ${mention_personage} теперь знает вкус неожиданности.",
    "Бокал из <code>${from_group}</code> летит по дуге и смачно приземляется на ${mention_personage}.",
    "Из <code>${from_group}</code> прилетает бокал — ${mention_personage} получает неожиданное сотрясение.",
]
throwDishFromGroup = [
    "Внезапно из <code>${from_group}</code> прилетает тарелка прямо в спящего ${mention_personage}!",
    "Из <code>${from_group}</code> прилетает тарелка — ${mention_personage} теперь знает вкус неожиданности.",
    "Кто-то из <code>${from_group}</code> метко отправляет тарелку прямо в ${mention_personage}!",
    "Из <code>${from_group}</code> прилетает тарелка — остатки ужина теперь на ${mention_personage}.",
    "Из <code>${from_group}</code> прилетает тарелка — ${mention_personage} теперь украшен остатками трапезы.",
    "Тарелка из <code>${from_group}</code> наносит неожиданное сотрясение ${mention_personage}.",
]
