topRaidWeek = """\
🏆Топ всех Искателей в рейдах за неделю <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Всего участников: ${total_count}"""
topRaidWeekGroup = """\
🏆Топ Искателей в группе в рейдах за неделю <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Всего участников: ${total_count}"""
topRaidPosition = "${position}. ${personage_badge_with_name}: ${success_raids}/${all_raids}"
topGroupRaidWeek = """\
🏆Топ Групп в рейдах за неделю <code>${start_date} - ${end_date}</code>:

${top_group_list}

Всего групп: ${total_count}"""
topGroupRaidPosition = "${position}. ${group_badge_with_name}: ${success_raids}/${all_raids}"
topRaidEmpty = "Никто не участвовал в рейдах за выбранный период"
topList = """\
📊Список топов доступных к просмотру:

🔰Топы Искателей:
🗡Топ Искателей в рейдах за неделю ${top_raid_week_command}
🗡Топ Искателей группы в рейдах за неделю ${top_raid_week_group_command}
⚒Топ работяг в группе ${top_work_group_command}
💪 Топ Искателей в группе по мощи ${top_power_personage_command}

👥Топы Групп:
🗡Топ Групп в рейдах за неделю ${top_group_raid_week_command}"""
topWorkerOfDayEmpty = "Никто ещё не был назначен работягой в этой группе."
topWorkerOfDayGroup = """\
⚒Топ работяг в группе за всё время:

${top_personage_list}

Всего участников: ${total_count}
"""
topWorkerPosition = "${position}. ${personage_badge_with_name}: ${work_count}"

topPowerPersonageGroup = """\
💪Топ Искателей в группе по мощи:

${top_personage_list}

Всего участников: ${total_count}
"""
topPowerPersonagePosition = "${position}. ${personage_badge_with_name}: ${power}"
topPersonageEmpty = "Нет участников для отображения"
topWorldRaidResearch = """\
🏆Топ Искателей по вкладу поиска мирового рейда:

${top_personage_list}

Всего участников: ${total_count}"""
topWorldRaidResearchPosition = "${position}. ${personage_badge_with_name}: ${contribution} ${optional_reward}"
topWorldRaidResearchReward = " +${money_icon}${reward}"
topWorldRaidResearchEmpty = "Пока никто не сделал вклад в поиск рейда"
