notEnoughUsers = """\
Для торжественного объявления Работяги дня необходимо собрать хотя бы минимальную группу: ${required_users}! \
Просто покажите удостоверение через /me"""
alreadyChosen = [
    "На сегодня место главного работяги занято ${mention_personage_badge_with_name}",
    "Все работяги уже распределены. Сегодня это ${mention_personage_badge_with_name}. Приходите завтра!"
]
chosenUser = """\
${chosen_user_text}
<i>Эффект: ${effect}</i>"""

chosenUserVariations = [
    "Теперь ${mention_personage_badge_with_name} в рядах работяг Крезара, вот лопата, вот могилы!",
    "Работяга дня - ${mention_personage_badge_with_name}! Занимается отшкребыванием зубастых грибов у бабы Зины на даче.",
    """\
Добро пожаловать в ряды работяг, ${mention_personage_badge_with_name}! \
Туалеты тут, вилку в зубы и вот так вот раз-раз, раз-раз!""",
    """\
Новая задача для работяги! Как известно волк в цирке не выступает, \
а ${mention_personage_badge_with_name} с удовольствием заменит его сегодня на арене!""",
    """\
Барды всю ночь драли глотки. Сегодня работяге ${mention_personage_badge_with_name} \
предстоит смазать все гортани музыкантов для дальнейшей эксплуатации.""",
    """\
Работа не волк, да и ${mention_personage_badge_with_name} не волк. \
Просто настоящий работяга — давайте хотя бы сегодня это признаем!""",
    "Э, ${mention_personage_badge_with_name}, вставай. Вставай, бля, задолбал, на работу пора.",
    "Работать, ${mention_personage_badge_with_name}! Солнце ещё высоко! Задача на сегодня: копать от забора и до обеда.",
]
