[[badge]]
code = "standard"

[badge.locales.RU]
description = "Стандартный жетон Искателя"

[[badge]]
code = "first-personages"

[badge.locales.RU]
description = "Первые Искатели"

[[badge]]
code = "first-season"

[badge.locales.RU]
description = "Первый Сезон"

[[badge]]
code = "second-season"

[badge.locales.RU]
description = "Второй Сезон"

[[badge]]
code = "new-year-2025"

[badge.locales.RU]
description = "Новый Год 2025"

[[badge]]
code = "third-season"

[badge.locales.RU]
description = "Третий Сезон"

[[badge]]
code = "first-groups"

[badge.locales.RU]
description = "Первые группы"
