[[badge]]
code = "standard"

[badge.locales.RU]
description = "Стандартный жетон Искателя"

[[badge]]
code = "first-personages"

[badge.locales.RU]
description = "Первые Искатели"

[[badge]]
code = "first-season"

[badge.locales.RU]
description = "Первый Сезон"
