# Сам предмет, который описывают модификаторы выше
[[object]]
code = "sword"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Меч"
form = "MASCULINE"

[object.locales.EN]
text = "Sword"
form = "WITHOUT"

[[object]]
code = "club"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Палица"
form = "FEMININE"

[object.locales.EN]
text = "Club"
form = "WITHOUT"

[[object]]
code = "spear"
slots = ["MAIN_HAND", "OFF_HAND"]
characteristics.attack = "4-10"

[object.locales.RU]
text = "Копьё"
form = "NEUTER"

[object.locales.EN]
text = "Spear"
form = "WITHOUT"

[[object]]
code = "dagger"
slots = ["OFF_HAND"]
characteristics.attack = "1-5"

[object.locales.RU]
text = "Кинжал"
form = "MASCULINE"

[object.locales.EN]
text = "Dagger"
form = "WITHOUT"

[[object]]
code = "cutlass"
slots = ["OFF_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Кортик"
form = "MASCULINE"

[object.locales.EN]
text = "Cutlass"
form = "WITHOUT"

[[object]]
code = "stick"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Палка"
form = "FEMININE"

[object.locales.EN]
text = "Stick"
form = "WITHOUT"

[[object]]
code = "saber"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Сабля"
form = "FEMININE"

[object.locales.EN]
text = "Saber"
form = "WITHOUT"

[[object]]
code = "shield"
slots = ["OFF_HAND"]
characteristics.defense = "1-5"

[object.locales.RU]
text = "Щит"
form = "MASCULINE"

[object.locales.EN]
text = "Shield"
form = "WITHOUT"

[[object]]
code = "vest"
slots = ["BODY"]
characteristics.defense = "1-5"
characteristics.health = "10-20"

[object.locales.RU]
text = "Жилетка"
form = "FEMININE"

[object.locales.EN]
text = "Vest"
form = "WITHOUT"

[[object]]
code = "cuirass"
slots = ["BODY"]
characteristics.defense = "4-10"
characteristics.health = "20-40"

[object.locales.RU]
text = "Кираса"
form = "FEMININE"

[object.locales.EN]
text = "Cuirass"
form = "WITHOUT"

[[object]]
code = "chain-mail"
slots = ["BODY"]
characteristics.defense = "5-13"
characteristics.health = "15-30"

[object.locales.RU]
text = "Кольчуга"
form = "FEMININE"

[object.locales.EN]
text = "Mail"
form = "WITHOUT"

[[object]]
code = "pants"
slots = ["PANTS"]
characteristics.defense = "1-10"
characteristics.health = "10-40"

[object.locales.RU]
text = "Штаны"
form = "PLURAL"

[object.locales.EN]
text = "Pants"
form = "WITHOUT"

[[object]]
code = "socks"
slots = ["SHOES"]
characteristics.defense = "1-3"
characteristics.health = "5-10"

[object.locales.RU]
text = "Носки"
form = "PLURAL"

[object.locales.EN]
text = "Socks"
form = "WITHOUT"

[[object]]
code = "boots"
slots = ["SHOES"]
characteristics.defense = "2-8"
characteristics.health = "10-20"

[object.locales.RU]
text = "Сапоги"
form = "PLURAL"

[object.locales.EN]
text = "Boots"
form = "WITHOUT"

[[object]]
code = "hat"
slots = ["HELMET"]
characteristics.defense = "2-6"
characteristics.health = "5-20"

[object.locales.RU]
text = "Шляпа"
form = "FEMININE"

[object.locales.EN]
text = "Hat"
form = "WITHOUT"

[[object]]
code = "helmet"
slots = ["HELMET"]
characteristics.defense = "5-10"
characteristics.health = "10-25"

[object.locales.RU]
text = "Шлем"
form = "MASCULINE"

[object.locales.EN]
text = "Helmet"
form = "WITHOUT"

[[object]]
code = "gloves"
slots = ["GLOVES"]
characteristics.defense = "5-10"
characteristics.health = "10-25"

[object.locales.RU]
text = "Перчатки"
form = "PLURAL"

[object.locales.EN]
text = "Gloves"
form = "WITHOUT"

[[object]]
code = "boxers"
slots = ["PANTS"]
characteristics.defense = "1-5"
characteristics.health = "5-25"

[object.locales.RU]
text = "Семейники"
form = "PLURAL"

[object.locales.EN]
text = "Boxers"
form = "WITHOUT"
