# Есть два типа модификаторов, FIRST и SECOND, разделение идёт по порядку слов в русском языке
[[modifier]]
code = "sharp"
type = "PREFIX"
characteristics.attack = "3-6"

[modifier.locales.RU.form]
MASCULINE = "Острый"
FEMININE = "Острая"
NEUTER = "Острое"
PLURAL = "Острые"

[modifier.locales.EN.form]
WITHOUT = "Sharp"

[[modifier]]
code = "iron"
type = "PREFIX"
characteristics.multiplier = "1.5-1.8"

[modifier.locales.RU.form]
MASCULINE = "Железный"
FEMININE = "Железная"
NEUTER = "Железное"
PLURAL = "Железные"

[modifier.locales.EN.form]
WITHOUT = "Iron"

[[modifier]]
code = "wooden"
type = "PREFIX"
characteristics.multiplier = "1.1-1.3"

[modifier.locales.RU.form]
MASCULINE = "Деревянный"
FEMININE = "Деревянная"
NEUTER = "Деревянное"
PLURAL = "Дервянные"

[modifier.locales.EN.form]
WITHOUT = "Wooden"

[[modifier]]
code = "strength"
type = "SUFFIX"
characteristics.attack = "4-8"

[modifier.locales.RU.form]
WITHOUT = "Силы"

[modifier.locales.EN.form]
WITHOUT = "Of Strength"

[[modifier]]
code = "anger"
type = "SUFFIX"
characteristics.attack = "3-7"

[modifier.locales.RU.form]
WITHOUT = "Гнева"

[modifier.locales.EN.form]
WITHOUT = "Of Anger"

[[modifier]]
code = "random"
type = "SUFFIX"
characteristics.attack = "1-10"

[modifier.locales.RU.form]
WITHOUT = "Случайности"

[modifier.locales.EN.form]
WITHOUT = "Of Random"

[[modifier]]
code = "holiday"
type = "PREFIX"
characteristics.multiplier = "1.3-1.7"

[modifier.locales.RU.form]
MASCULINE = "Праздничный"
FEMININE = "Праздничная"
NEUTER = "Праздничное"
PLURAL = "Праздничные"

[modifier.locales.EN.form]
WITHOUT = "Holiday"
