# Сам предмет, который описывают модификаторы выше
[[object]]
code = "sword"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Меч"
form = "MASCULINE"

[object.locales.EN]
text = "Sword"
form = "WITHOUT"

[[object]]
code = "club"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Палица"
form = "FEMININE"

[object.locales.EN]
text = "Club"
form = "WITHOUT"

[[object]]
code = "spear"
slots = ["MAIN_HAND", "OFF_HAND"]
characteristics.attack = "4-10"

[object.locales.RU]
text = "Копьё"
form = "NEUTER"

[object.locales.EN]
text = "Spear"
form = "WITHOUT"

[[object]]
code = "dagger"
slots = ["OFF_HAND"]
characteristics.attack = "1-5"

[object.locales.RU]
text = "Кинжал"
form = "MASCULINE"

[object.locales.EN]
text = "Dagger"
form = "WITHOUT"

[[object]]
code = "cutlass"
slots = ["OFF_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Кортик"
form = "MASCULINE"

[object.locales.EN]
text = "Cutlass"
form = "WITHOUT"

[[object]]
code = "stick"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Палка"
form = "FEMININE"

[object.locales.EN]
text = "Stick"
form = "WITHOUT"

[[object]]
code = "saber"
slots = ["MAIN_HAND"]
characteristics.attack = "2-6"

[object.locales.RU]
text = "Сабля"
form = "FEMININE"

[object.locales.EN]
text = "Saber"
form = "WITHOUT"

[[object]]
code = "shield"
slots = ["OFF_HAND"]
characteristics.defense = "1-5"

[object.locales.RU]
text = "Щит"
form = "MASCULINE"

[object.locales.EN]
text = "Shield"
form = "WITHOUT"
