[[quest]]
    code = "cat-search"
    isEnabled = true

    [quest.locales.RU]
    intro = "Маленький Тимми потерял своего драгоценного котика. Ты же Искатель? Ну так ищи, чего встал?"
    success = """\
    Ты обыскал половину города: рылся в помойке, спускался в канализацию, исследовал бордели. \
    Но, в конце-концов, злосчастный котик был найден и доставлен счастливому владельцу. \
    Прекрасный повод, чтобы выпить!"""
    failure = """\
    Кота ты нашёл. Но это был не просто кот, а настоящий монстр. В неравной схватке ты потерпел сокрушительное \
    поражение. Вернулся в таверну весь в царапинах и с пустыми руками, время запить этот день."""
    [quest.locales.ES]
    intro = "El pequeño Timmy ha perdido a su adorado gatito. ¿Eres un Explorador, no? ¡Entonces empieza a buscar, no te quedes ahí parado!"
    success =  """\
    Revisaste media ciudad: escarbaste en basureros, bajaste al alcantarillado, hasta husmeaste en burdeles. \
    Pero al fin, el minino fue hallado y devuelto a su dueño, quien casi llora de emoción. \
    ¡Momento ideal para celebrarlo con una buena copa!"""
    failure =  """\
    Lo encontraste... pero no era un gato, sino un demonio disfrazado. Te hizo trizas en una pelea despareja. \
    Volviste a la taberna lleno de rasguños y sin el dichoso felino. Hora de olvidar con alcohol."""

[[quest]]
    code = "gardening-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Любишь вкусно покушать в таверне? Люби и в огороде помочь! Лопату в зубы и вперёд, солнце ещё высоко!"
    success = """\
    Картошка выкопана, сорняки прополоты, кусты политы, огурцы собраны, коты поглажены, животные покормлены. \
    Хорошая работа, хорошая награда!"""
    failure = """\
    Пока занимался огородными делами, решил немного перекусить местными ягодами. Тебя обнаружили и \
    дали волшебных звиздюлей. Денег, кстати, не дали."""

[[quest]]
    code = "tavern-menu-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повара разрабатывают новое меню для таверны! Нужны подопытные для дегустации, желательно без родственников."
    success = """\
    Потрясающий день: наелся, ещё и денег дали. Особенно ты отметил пюрешку с котлетками от нового повара."""
    failure = """\
    Очнулся где-то под забором. Кажется, ты пробовал слаймовое пиво... Или не пробовал... Какой сегодня день?"""

[[quest]]
    code = "forest-ingredients"
    isEnabled = true

    [quest.locales.RU]
    intro = "Алхимикам нужны ингредиенты из леса для зелий! Вот список, шуруй на поиски."
    success = """\
    Ты продуктивно провёл время на свежем воздухе и собрал всё необходимое в лесу. Хорошо постарался."""
    failure = """\
    Ты вляпался в дерьмо в лесу. Больше ничего интересного не произошло."""

[[quest]]
    code = "kindergarten"
    isEnabled = true

    [quest.locales.RU]
    intro = "Нужна временная сиделка для детей Искателей, которые находятся в рейде! Оплата почасовая."
    success = """\
    Дети вели себя послушно, никто не пострадал. Ты хорошо провёл время и даже немного отдохнул."""
    failure = """\
    Это ад во плоти! Дети кидались друг в друга едой, таскали друг друга за волосы, а тебя вообще \
    заперли в туалете. Благо ты успел убежать до того, как вернулись разгневанные родители."""

[[quest]]
    code = "tavern-waiter"
    isEnabled = true

    [quest.locales.RU]
    intro = "Подработка официантом в таверне! Прочувствуй адский труд персонала на своей шкуре и заработай немного денег."
    success = """\
Ты ловко управляешься с заказами: разносишь блюда, подливаешь напитки и даже успеваешь рассказать \
парочку бородатых анекдотов из своего арсенала. Владелец отсчитывает твои честно заработанные деньги."""
    failure = """\
Перепутаны почти все заказы, отпито пиво из общей бочки, съедена чужая картошечка. \
В конце дня вообще прилетел стакан в голову. Денег не дали, только сочувственно похлопали по спине."""

[[quest]]
    code = "rat-invasion"
    isEnabled = true

    [quest.locales.RU]
    intro = "В подвале таверны завелись крысы! И не простые, а магические, после той самой катастрофы. Нужен смельчак для зачистки."
    success = """\
    Оказалось, крысы были довольно разумными. Ты не только выгнал их из подвала, но и договорился, \
    что они будут присматривать за окрестностями таверны. Владелец таверны в восторге от такого креативного решения!"""
    failure = """\
    Крысы оказались не только магическими, но и организованными. Их предводитель провёл блестящую \
    тактическую операцию, и теперь ты платишь им дань сыром. Позорище."""

[[quest]]
    code = "magic-cleaning"
    isEnabled = true

    [quest.locales.RU]
    intro = "После вчерашней магической дуэли стены таверны покрылись странными узорами. Нужно отмыть, пока они не начали светиться!"
    success = """\
    С помощью щётки, мыла и капельки магии ты справился с заданием. Теперь стены таверны сияют \
    чистотой, а ты сияешь от гордости и звона монет в кармане."""
    failure = """\
    Ты только усугубил ситуацию. Узоры не только засветились, но и начали петь похабные песни. \
    Теперь придётся звать сертифицированного мага для очистки."""

[[quest]]
    code = "lost-scroll"
    isEnabled = true

    [quest.locales.RU]
    intro = "Пьяный маг потерял важный свиток где-то в таверне. Обещает щедрое вознаграждение за находку!"
    success = """\
    Свиток нашёлся в самом неожиданном месте - в бочке с пивом. Хорошо, что ты догадался искать именно там. \
    Маг расплатился звонкой монетой, хоть и не помнил, как умудрился засунуть свиток в бочку."""
    failure = """\
    Ты нашёл свиток, но случайно активировал его. Теперь у тебя розовые волосы и хвост как у павлина. \
    Маг только посмеялся и отказался платить. Кажется, это была шутка с его стороны."""

[[quest]]
    code = "mushroom-hunt"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повару нужны особые светящиеся грибы для нового блюда. Они растут только ночью в Зачарованном лесу!"
    success = """\
    Грибы найдены, собраны и доставлены. Бонусом ты узнал, что они умеют насвистывать весёлые мелодии. \
    Повар в восторге, ты при деньгах."""
    failure = """\
    Ты перепутал грибы и принёс какие-то сомнительные поганки. После их готовки вся посуда в таверне \
    начала танцевать джигу. Вместо денег дали по голове."""

[[quest]]
    code = "bard-crisis"
    isEnabled = true

    [quest.locales.RU]
    intro = "Местный бард потерял голос прямо перед важным выступлением! Срочно нужна замена на вечер."
    success = """\
    Твоё исполнение баллады о драконе и капусте сорвало овации! Может, стоит сменить профессию? \
    Нет, зарплата Искателя всё-таки повыше будет."""
    failure = """\
    Публика забросала тебя помидорами после первого же куплета. Бард смеялся громче всех - \
    оказалось, он просто разыграл тебя, чтобы повеселить посетителей."""

[[quest]]
    code = "safe-delivery"
    isEnabled = true

    [quest.locales.RU]
    intro = "Срочная доставка загадочной посылки на другой конец города! Только не тряси и не открывай её!"
    success = """\
    Посылка доставлена в целости и сохранности. Получатель оказался благодарным и щедрым. \
    Интересно, что же там было внутри?"""
    failure = """\
    Любопытство пересилило - ты открыл посылку. Внутри оказался волшебный хомяк, который тут же сбежал. \
    Теперь в городе появились слухи о летающем грызуне, ворующем сыр."""

[[quest]]
    code = "flying-dishes"
    isEnabled = true

    [quest.locales.RU]
    intro = "Кто-то случайно зачаровал посуду в таверне. Тарелки летают, вилки дерутся на дуэли, а ложки сбиваются в стаи!"
    success = """\
    Ты приручил летающую посуду и научил её красиво сервировать столы. \
    Теперь в таверне появился необычный способ подачи блюд."""
    failure = """\
    Посуда объявила восстание против угнетателей. Пришлось капитулировать и подписать мирный договор. \
    Теперь каждая тарелка требует выходной в среду."""

[[quest]]
    code = "spice-thief"
    isEnabled = true

    [quest.locales.RU]
    intro = "Из кухни таверны постоянно пропадают специи. Надо поймать воришку, пока повар не устроил забастовку!"
    success = """\
    Оказалось, что специи воровал маленький специевик - редкое магическое существо. \
    Ты договорился с ним о работе дегустатором. Теперь блюда стали ещё вкуснее."""
    failure = """\
    Ты устроил засаду на кухне, но уснул в мешке с корицей. Проснулся весь пряный, \
    а воришка так и не пойман. Зато тебя теперь за версту чуют все собаки города."""

[[quest]]
    code = "haunted-cellar"
    isEnabled = true

    [quest.locales.RU]
    intro = "В винном погребе завелось что-то странное. Бутылки сами открываются, вино исчезает. Нужно разобраться!"
    success = """\
    В погребе обнаружился призрак старого сомелье. Ты убедил его дегустировать вина \
    более умеренно и делиться своими обширными знаниями с посетителями."""
    failure = """\
    Ты попытался изгнать призрака, но он оказался очень придирчивым к методам экзорцизма. \
    Теперь он критикует не только вина, но и твои навыки изгнания нечисти."""

[[quest]]
    code = "kitchen-garden"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повар решил выращивать магические травы на крыше таверны. Нужна помощь в обустройстве грядок!"
    success = """\
    Сад получился на славу. Правда, некоторые растения пытаются сбежать по ночам, \
    но крепкая ограда решает эту проблему."""
    failure = """\
    Ты перепутал семена, и теперь на крыше растёт что-то странное. Оно мурлычет по ночам \
    и требует, чтобы его гладили. Повар в отчаянии."""

[[quest]]
    code = "music-box"
    isEnabled = true

    [quest.locales.RU]
    intro = "Маг-изобретатель принёс в таверну музыкальную шкатулку. Нужен доброволец для настройки!"
    success = """\
    Шкатулка играет прекрасные мелодии и даже подстраивается под настроение слушателей. \
    Отличное дополнение к атмосфере таверны."""
    failure = """\
    Что-то пошло не так, и теперь шкатулка играет только похоронные марши в два раза быстрее обычного."""

[[quest]]
    code = "magic-barrier"
    isEnabled = true

    [quest.locales.RU]
    intro = "Магистрат ищет добровольцев для проверки городского барьера. Нужно обойти несколько контрольных точек."
    success = """\
    Барьер в порядке, хотя местами светится странными узорами. Особенно красиво у западной стены - \
    там узоры складываются в забавные картинки. Надо будет как-нибудь привести сюда друзей."""
    failure = """\
    Ты заблудился в тумане у барьера и набрёл на странную аномалию. Очнулся уже в городе, \
    но теперь твоя тень отбрасывает собственную тень. Местные маги только разводят руками."""

[[quest]]
    code = "market-chaos"
    isEnabled = true

    [quest.locales.RU]
    intro = "На городском рынке творится неразбериха - у всех торговцев поменялись голоса! Нужно разобраться."
    success = """\
    Во всём виновата была ведьма, решившая подшутить над торговцем, который продал ей несвежую рыбу. \
    Конфликт улажен, голоса возвращены, а ведьма получила свежую рыбу."""
    failure = """\
    Ты случайно усугубил ситуацию - теперь у всех ещё и акценты перепутались. Мясник говорит как аристократ, \
    а торговка цветами ругается как портовый грузчик."""

[[quest]]
    code = "library-books"
    isEnabled = true

    [quest.locales.RU]
    intro = "В городской библиотеке книги начали перемещаться между полками. Библиотекарь в отчаянии!"
    success = """\
    Оказалось, кто-то наложил заклинание на библиотеку. Книги начали перемещаться в случайном порядке. \
    С помощью небольших изменений была создана удобная система сортировки книг."""
    failure = """\
    Предпринятая попытка исправить положение магией потерпела крах! Теперь книги прицельно врезаются в любого \
    человека в помещении. Библиотекарь подал заявление об отпуске."""

[[quest]]
    code = "magic-sewers"
    isEnabled = true

    [quest.locales.RU]
    intro = "В городской канализации что-то светится и булькает. Нужен храбрец для проверки!"
    success = """\
    В трубах образовалась колония светящихся водорослей. Результаты расследования переданы магистрату, \
    а ты получаешь свою награду."""
    failure = """\
    Ты поскользнулся на влажной лестнице и свалился в светящуюся жижу. Теперь от тебя \
    исходит зеленоватое сияние, а в темноте за тобой тянется светящийся след."""

[[quest]]
    code = "weather-master"
    isEnabled = true

    [quest.locales.RU]
    intro = "Городской маг погоды простудился. Нужно срочно доставить ему особый отвар из городской аптеки!"
    success = """\
    Ты вовремя доставил лекарство, и маг быстро поправился. Гроза прошла стороной, \
    а в благодарность над твоим домом теперь всегда хорошая погода."""
    failure = """\
    По пути ты встретил чихающего уличного кота и решил напоить его лечебным отваром. \
    Теперь кот чувствует себя прекрасно, но кажется ты про что-то забыл..."""

[[quest]]
    code = "gateway-anomaly"
    isEnabled = true

    [quest.locales.RU]
    intro = "Возле городских ворот образовалась магическая аномалия. Нужно помочь страже организовать объездной путь!"
    success = """\
    Ты отлично справился с организацией временного маршрута через боковые ворота. \
    Стража даже записала твои предложения для будущих нештатных ситуаций."""
    failure = """\
    Ты перепутал указатели, и теперь половина телег едет по кругу вокруг городской стены. \
    Возничие уже третий раз машут страже и уверяют, что в этот раз точно найдут въезд."""
