[[quest]]
    code = "cat-search"
    isEnabled = true

    [quest.locales.RU]
    intro = "Маленький Тимми потерял своего драгоценного котика. Ты же Искатель? Ну так ищи, чего встал?"
    success = """\
    Ты обыскал половину города: рылся в помойке, спускался в канализацию, исследовал бордели. \
    Но, в конце-концов, злосчастный котик был найден и доставлен счастливому владельцу. \
    Прекрасный повод, чтобы выпить!"""
    failure = """\
    Кота ты нашёл. Но это был не просто кот, а настоящий монстр. В неравной схватке ты потерпел сокрушительное \
    поражение. Вернулся в таверну весь в царапинах и с пустыми руками, время запить этот день."""

[[quest]]
    code = "gardening-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Любишь вкусно покушать в таверне? Люби и в огороде помочь! Лопату в зубы и вперёд, солнце ещё высоко!"
    success = """\
    Картошка выкопана, сорняки прополоты, кусты политы, огурцы собраны, коты поглажены, животные покормлены. \
    Хорошая работа, хорошая награда!"""
    failure = """\
    Пока занимался огородными делами, решил немного перекусить местными ягодами. Тебя обнаружили и \
    дали волшебных звиздюлей. Денег, кстати, не дали."""

[[quest]]
    code = "tavern-menu-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повара разрабатывают новое меню для таверны! Нужны подопытные для дегустации, желательно без родственников."
    success = """\
    Потрясающий день: наелся, ещё и денег дали. Особенно ты отметил пюрешку с котлетками от нового повара."""
    failure = """\
    Очнулся где-то под забором. Кажется, ты пробовал слаймовое пиво... Или не пробовал... Какой сегодня день?"""

[[quest]]
    code = "forest-ingredients"
    isEnabled = true

    [quest.locales.RU]
    intro = "Алхимикам нужны ингредиенты из леса для зелий! Вот список, шуруй на поиски."
    success = """\
    Ты продуктивно провёл время на свежем воздухе и собрал всё необходимое в лесу. Хорошо постарался."""
    failure = """\
    Ты вляпался в дерьмо в лесу. Больше ничего интересного не произошло."""

[[quest]]
    code = "kindergarten"
    isEnabled = true

    [quest.locales.RU]
    intro = "Нужна временная сиделка для детей Искателей, которые находятся в рейде! Оплата почасовая."
    success = """\
    Дети вели себя послушно, никто не пострадал. Ты хорошо провёл время и даже немного отдохнул."""
    failure = """\
    Это ад во плоти! Дети кидались друг в друга едой, таскали друг друга за волосы, а тебя вообще \
    заперли в туалете. Благо ты успел убежать до того, как вернулись разгневанные родители."""

[[quest]]
    code = "tavern-waiter"
    isEnabled = true

    [quest.locales.RU]
    intro = "Подработка официантом в таверне! Прочувствуй адский труд персонала на своей шкуре и заработай немного денег."
    success = """\
Ты ловко управляешься с заказами: разносишь блюда, подливаешь напитки и даже успеваешь рассказать \
парочку бородатых анекдотов из своего арсенала. Владелец отсчитывает твои честно заработанные деньги."""
    failure = """\
Перепутаны почти все заказы, отпито пиво из общей бочки, съедена чужая картошечка. \
В конце дня вообще прилетел стакан в голову. Денег не дали, только сочувственно похлопали по спине."""
